#include<stdio.h>
#include<math.h>
intmain(){
floata=0.01,b=1.5∗M_PI,x,delta_x=1.e−3/∗0.001∗/,funkca,funkcb,funkcx;
intk=0;
funkca=sin(a);funkcb=sin(b);
if(funkca∗funkcb>0){
printf(”Intervaalaa[%.2f;%.2f]sin(x)funkcijai”,a,b);
printf(”saknjunav(vaitaajaairpaarusaknjuskaits)\n”);
return1;}
printf(”sin(%7.3f)=%7.3f\t\t\t\t”,a,sin(a));
printf(”sin(%7.3f)=%7.3f\n”,b,sin(b));

16while((b−a)>delta_x){
17k++;//k=k+1;//k+=1;
18x=(a+b)/2.;
19if(funkca∗sin(x)>0)//piea=0−>funkca=0−>reizinaajumsirpreciizi0
visulaiku−>visulaika”straadaa”b=x
20a=x;
21else
22b=x;
23printf(”%2d.iteraacija:sin(%7.3f)=%7.3f\t”,k,a,sin(a));
24printf(”sin(%7.3f)=%7.3f\t”,x,sin(x));
25printf(”sin(%7.3f)=%7.3f\n”,b,sin(b));}
26
27printf(”Saakneatrodaspiex=%.3f,josin(x)ir%.3f\n”,x,sin(x));
28
29return0;}